name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "pnpm"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist